# replace the <full url of the public repository> with your repository url.
# replace the <branch name> with the branch name used for publishing site, usually master branch.

# repositoryUrl: <full url of the public repository>/blob/<branch name>
repositoryUrl: https://github.com/Dynamsoft/company-docs/blob/main


# Full url of the publicshed site without last '/'.
# For example: the full url of dbr doc sit is https://www.dynamsoft.com/barcode-reader/
# then set docFullPath with https://www.dynamsoft.com/barcode-reader

# docFullPath: <full url of the published site> (eg - https://www.dynamsoft.com/barcode-reader)
docFullPat: https://www.dynamsoft.com/company/docs

# Relative path to first-level domain name without last '/'.
# For example: the full url of dbr doc sit is https://www.dynamsoft.com/barcode-reader/
# then set firstLevelUrl with /barcode-reader

# firstLevelUrl: #<relative path to first-level domain> (eg - /barcode-reader)
firstLevelUrl: /company/docs

# docHomePage: #<relative path of homepage to first-level domain>
# if index.md in the repo is the homepage, set the value same as firstLevelUrl.
docHomePage: /company/docs

# Notice the root of the path is the first-level domain, so the relative path shall be started 
# with the first-level path rather than the root path of the repository.

# Example variable:

# sampleFolder: <firstLevelUrl>/sample-folder/
customer-portal-faq: /company/docs/customer-portal-faq/


# public resources.

# assets: <firstLevelUrl>/assets/
assets: /company/docs/assets/
# edit_icon: <firstLevelUrl>/assets/img-icon/edit-icon.png
edit_icon: /company/docs/assets/img-icon/edit-icon.png
# smile_icon: <firstLevelUrl>/assets/img-icon/icon-smile.png
smile_icon: /company/docs/assets/img-icon/icon-smile.png
# sad_icon: <firstLevelUrl>/assets/img-icon/icon-sad.png
sad_icon: /company/docs/assets/img-icon/icon-sad.png
# dbr_icon: <firstLevelUrl>/assets/img-icon/icon-dbr.svg
dbr_icon: /company/docs/assets/img-icon/icon-dbr.svg
# dwt_icon: <firstLevelUrl>/assets/img-icon/icon-dwt.svg
dwt_icon: /company/docs/assets/img-icon/icon-dwt.svg
# dnt_icon: <firstLevelUrl>/assets/img-icon/icon-dnt.svg
dnt_icon: /company/docs/assets/img-icon/icon-dnt.svg


# Replace the <firstLevelUrl> with the value of firstLevelUrl defined above.

# baseurl: "<firstLevelUrl>"
baseurl: "/company/docs"

plugins:
  - jemoji